name: 'energymix'
version: '1.0.0'

profile: 'energymix'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  energymix:
    energymix:
      +materialized: view

flags:
  send_anonymous_usage_stats: False
